### ISSUE TITLE
Merge fields not working properly with PUT request

### ISSUE THREAD

**Issue by onkstudio** [drewm/mailchimp-api#92] opened 2016-04-07 16:56 UTC
Hi,

Thanks for your work, it is working great and very useful !

I am having an issue though with the PUT request :

```php
$mc = new MailChimp($api_key);
$list_id = '123456789'; // not the real one obviously
$subscriber_hash = $mc->subscriberHash($email);
$result = $mc->put("lists/$list_id/members/$subscriber_hash", [
   'email_address' => $email,
   'status'        => 'subscribed',
   'merge_fields' => ["FNAME" => $firstname, "LNAME" => $lastname],
   'status_if_new' => 'subscribed'
]);
```

The request works fine by adding a new member to the list or updating one if already existing, but the FNAME merge field is not taken into account... I can assure you the $firstname variable is not empty (I also tried with a fixed string value).
The returned array contains the following entry:

_[merge_fields] => Array ( [FNAME] => [LNAME] => DOE )_

The same request using a POST action does work fine, so the FNAME merge field is configured properly on MailChimp side. But I have to use the PUT action since it is the only one allowing a previously deleted email to be added again.
I have tried switching the order of the merge fields with no success, the same FNAME field still does not work.

Can you be of any help or is this a MailChimp-related bug ?

Thank you in advance !

**Comment by johnprice99** [comment] 2016-04-08 09:50
I have the exact same issue, and it appears to happen only when using PUT to create the subscriber, any subsequent calls to the API with same details will update the FNAME correctly.

This is definitely not a bug in the PHP client, as the same thing happens when using cURL directly:

`curl -X PUT -H "Content-Type: application/json" -H "Authorization: apikey <API-KEY>" -H "Cache-Control: no-cache" -d '{"email_address":"testemail@test.com","merge_fields":{"FNAME":"John","LNAME":"Price"},"status":"subscribed"}' "https://<dc>.api.mailchimp.com/3.0/lists/<LIST-ID>/members/<subscriber-hash>"`

**Comment by drewm** [comment] 2016-04-08 14:40
Thanks for the info @johnprice99. As it's an API bug/issue, I'll close this for now.

**Closed by drewm** 2016-04-08 14:40 UTC

**Comment by jimblue** [comment] 2018-01-13 03:12
I know it's an API bug, but still having this issue... do you guys have some update about it?

**Comment by johnprice99** [comment] 2018-01-15 14:24
@jimblue the issue was acknowledged by MailChimp support, and their suggestion until they can fix it (which unfortunately they had no timeline for) was to make the initial call, then make the call a second time to update the merge_fields.

**Comment by jimblue** [comment] 2018-01-15 15:02
Thanks @johnprice99 !
As MailChimp support can't found a fix for this basic bug for a year I've conclude this is probably not the best tool to choose.
I've just move to MailJet, way better in many case and they don't force you to display a badge like MailChimp does!

**Comment by keen4o** [comment] 2018-02-28 09:19
The code from the first post does work for me. I can update the info for my subscribers with PUT. I can show you my code if any one want.

**Comment by jasminechao** [comment] 2018-03-20 15:19
@keen4o I would be interested in seeing your code. I've been trying to update $FNAME and $LNAME for subscribers, but each new put overwrites the fields. Would appreciate your help!

**Comment by keen4o** [comment] 2018-03-22 07:52
My code works the same. If the email is the same as the email in my mailchimp account it does overwrites my fields too because the email is the unique field. If the email is new it just creates a new subscriber.

**Comment by thursdaydan** [comment] 2021-04-29 10:01
Hi, does anyone know if there has been any update on this issue from the Mailchimp side at all?
