### ISSUE TITLE
API v3 - PATCH: Schema describes array, object found instead

### ISSUE THREAD

**Issue by dregad** [drewm/mailchimp-api#54] opened 2015-08-18 23:04 UTC
Greetings,

I am test-driving the Mailchimp API v3 using your wrapper. Let me start by thanking you for making it available.

I'm getting an error when attempting to update a merge field using PATCH: 
``` php
$mc->patch("lists/$mailchimp_list_id/merge-fields/" . $field['merge_id'], $data);
```

This is the payload (`var_dump($json_data);` inserted just before `curl_exec()` call in MailChimp.php):
```
{"options":{"choices":{"0":"Aaa","1":"Bbb","2":"Ccc"}},"apikey":"xxxxxx-us5"}
```

Mailchimp is returning an error, as follows:
```
[title] => Invalid Resource
[status] => 400
[detail] => The resource submitted could not be validated. For field-specific details, see the 'errors' array.
[errors] => Array
	(
		[0] => Array
			(
				[field] => options.choices
				[message] => Schema describes array, object found instead
			)
	)
```

I suspect this is caused by use of *JSON_FORCE_OBJECT* in `json_encode()`. Not sure why you are using this option.

As a side note, removing *JSON_FORCE_OBJECT* yields a different error, but that one is most likely a Mailchimp issue...
```
[title] => Bad Request
[status] => 400
[detail] => This resource has not yet implemented array assignment for options.choices.
```

**Comment by adrian7** [comment] 2015-08-25 09:44
Bumped into the same issue today.

**Comment by drewm** [comment] 2015-08-26 09:28
I'll see if I can look into it. If anyone else has time to look at it, a PR would be very much appreciated.

**Comment by dregad** [comment] 2015-08-27 08:08
@drewm I could easily send a PR if you want to (the patch is trivial), but not knowing why you used the *JSON_FORCE_OBJECT* flag in the first place, I thought it would be better to open this issue and discuss things first instead. 

FYI, according to Mailchimp support, the 2nd error I'm getting is apparently a bug in the API, as per the e-mail I received from then on 19-Aug-2015:

> As the schema for that merge call specifies using an array, this is definitely unexpected. I've gone ahead and passed this information along to our developers so we can further investigate it. I wouldn't be able to provide an ETA on when we'll hear back from them, but as soon as they find a fix, they'll push it live.

> In the meantime, it would be possible to update those options using v2.0 of the API and the /lists/merge-var-update call. You can learn more about how that call is structured here:

> https://apidocs.mailchimp.com/api/2.0/lists/merge-var-update.php

Consequently, my only option for now is to stop using your wrapper and fall back on API v2... I will revisit this when that issue has been fixed on the Mailchimp side.

**Comment by drewm** [comment] 2015-08-27 08:15
It was added in PR #49 - so it looks like there's some subtlety to when it's needed and when it's not.

I don't have a current MailChimp project to test on (and I'm also standing in a field) but I might be able to look at it next week.

**Comment by adrian7** [comment] 2015-08-27 09:00
Not looked into it thoroughly, but looks like the error triggers when you send an empty array as `merge_fields`

**Comment by dregad** [comment] 2015-08-27 09:44
> looks like the error triggers when you send an empty array as `merge_fields`

@adrian7 not sure what you mean by that. My data array is most definitely not empty, as shown by the *var_dump* I introduced in the *patch* method (see above)

**Comment by liempro88** [comment] 2015-09-24 10:29
Seem now, i got same problem, but if rollback #49, it's ok :)

**Comment by sariabod** [comment] 2015-10-15 03:14
I also encountered this error when trying to create a new segment:
```php
 $MailChimp->post('lists/xxxxxx/segments', array(
                'name'     => 'api_test_segment',
                'options'  =>  array(
                                'match'=>'all',
                                'conditions'=>array(
                                        array('field'=>'EMAIL','op'=>'is','value'=>'john@example.com')
                                )
                        )
            ));
```
The api is expecting an array for the conditions items, but the JSON_FORCE_OBJECT flag turns the above into a non-valid request. If I remove the flag and do just a flat json_encode, the call works fine. It is quite possible the issue is an inconsistency on MC's part, but putting my experience here in case it helps.

**Comment by Jarlskov** [comment] 2015-11-13 08:39
The problem happens using batch processing as well, where the operations array is converted to an object, but the API expects an array.

**Comment by mykeysr** [comment] 2016-01-12 09:44
I've also encountered this error. So I removed the JSON_FORCE_OBJECT parameter.
and all works fine. :)

**Comment by wlcx** [comment] 2016-01-13 11:43
As far as I understand it, #49 appears to be entirely wrong; we *want* non-associative arrays to be encoded as JSON arrays, and associative arrays are *always* encoded to JSON objects, regardless of `JSON_FORCE_OBJECT`. However, the only potential gotcha (which #49 solves) is that empty arrays will be encoded to JSON arrays or JSON objects depending on JSON_FORCE_OBJECT, and I assume mailchimp does not accept empty arrays where it was expecting an object.
That said, my opinion is that the current behaviour is plain wrong, as the library generates no JSON arrays at all, while the API specifies them in several places.
A (hacky?) solution would be to make the json_encode `options` parameter an optional argument on this library's `get`, `post`, etc methods, allowing users to override the default on a per-call basis.

**Comment by relish27** [comment] 2016-01-13 16:03
I am also having this issue.  I am trying to create a campaign and I want to set conditions on a segment.  I'm getting the error on field "recipients.segment_opts.conditions" of "Schema describes array, object found instead."

**Comment by drewm** [comment] 2016-01-15 10:17
I've merged that PR - thanks @wlcx. Let me know if anyone still sees problems. If so, please give a code sample of the method you're using and I'll debug it from there.

**Closed** 2016-01-17 13:26 UTC
Labels: bug

**Comment by anaelChardan** [comment] 2016-02-18 21:02
Hi, I try to use you're API and I have exactly the same problem when I want to patch a merge-fields, have you any idea ? https://gist.github.com/anaelChardan/cb99da6c284196f31035. Thx !

**Comment by drewm** [comment] 2016-02-18 22:06
@anaelChardan for the interests, the MailChimp API docs say:

> The key of this object’s properties is the ID of the interest in question.

I think you'll find that to be accurate. You'll need to look up the ID of the interest and use it as the key.

```php
$MailChimp->patch("/lists/$list_id/members/$subscriber_hash", [
	'interests' => [
		'abcd1234' => true
	]
]);
```

If you have any further problems, please raise a new issue rather than posting to a months-old closed one! Thanks.
